apiVersion: v1
kind: Pod
metadata:
  name: exercise-pod-meta
spec:
  containers:
  - name: exercise-pod-meta
    image: poznajkubernetes/pkad:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
