apiVersion: v1
kind: Pod
metadata:
  name: init-exercise
spec:
  containers:
  - name: init-exercise
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name: workdir
        mountPath: /usr/share/nginx/html
  initContainers:
    - name: download-from-git
      image: docker.pkg.github.com/dikamilo/poznajkubernetes-playground/exercise:init-container
      imagePullPolicy: IfNotPresent
      command:
        - git
        - clone
        - "https://github.com/PoznajKubernetes/poznajkubernetes.github.io"
        - /work-dir
      volumeMounts:
        - name: workdir
          mountPath: /work-dir
  volumes:
    - name: workdir
      emptyDir: {}