apiVersion: v1
kind: Pod
metadata:
 name: two-containers
spec:
  restartPolicy: OnFailure
  containers:
  - image: poznajkubernetes/helloapp:multi
    name: helloapp
  - image: busybox
    name: busybox