apiVersion: v1
kind: Pod
metadata:
  name: exercise-pod-first-cm-env
spec:
  containers:
  - name: exercise-pod-first-cm-env
    image: poznajkubernetes/pkad:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - configMapRef:
          name: first-cm
