apiVersion: v1
kind: Pod
metadata:
  name: exercise-pod-secrets
spec:
  imagePullSecrets:
    - name: githubcreg
  containers:
  - name: exercise-pod-secrets
    image: docker.pkg.github.com/dikamilo/poznajkubernetes-playground/pkad:copy
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"