apiVersion: v1
kind: Pod
metadata:
  name: exercise-pod-secrets-usage
spec:
  containers:
  - name: exercise-pod-secrets-usage
    image: docker.pkg.github.com/dikamilo/poznajkubernetes-playground/pkad:copy
    envFrom:
      - secretRef:
          name: exercise-secret-literal
    volumeMounts:
      - mountPath: /secrets/
        name: secret-vol
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: secret-vol
      secret:
          secretName: exercise-secret-file
