apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: exercise-fanout
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /pkad/?(.*)
        backend:
          serviceName: exercise-fanout-pkad-service
          servicePort: 8080
      - path: /echo/?(.*)
        backend:
          serviceName: exercise-fanout-routing-echo-service
          servicePort: 8080