apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: exercise-fanout-host
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: pkad.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              serviceName: exercise-fanout-pkad-service
              servicePort: 8080
    - host: echo.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              serviceName: exercise-fanout-routing-echo-service
              servicePort: 8080