apiVersion: v1
kind: Pod
metadata:
  name: exercise-namespace
  labels:
    app: helloapp
spec:
  containers:
  - name: exercise-namespace
    image: poznajkubernetes/helloapp:svc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: exercise-namespace
spec:
  type: ClusterIP
  selector:
    app: helloapp
  ports:
  - port: 8080
    name: http