apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: exercise-job-multiple
spec:
  jobTemplate:
    metadata:
      name: exercise-job-multiple
    spec:
      parallelism: 2
      template:
        spec:
          containers:
          - image: busybox
            name: exercise-job-multiple
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
            command:
            - /bin/sh
            - -c
            - echo "job demo"
          restartPolicy: Never
  schedule: "*/1 * * * *"