apiVersion: v1
kind: Pod
metadata:
  name: exercise-multiple-labels-instance1
  labels:
    app: helloapp
    instance: one
spec:
  containers:
  - name: exercise-multiple-labels-instance1
    image: poznajkubernetes/helloapp:svc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: exercise-multiple-labels-instance2
  labels:
    app: helloapp
    instance: two
spec:
  containers:
  - name: exercise-multiple-labels-instance2
    image: poznajkubernetes/helloapp:svc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: exercise-multiple-labels
spec:
  type: NodePort
  selector:
    app: helloapp
    instance: one
  ports:
  - port: 8080
    name: http