apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-readiness-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: broken-readiness-deployment
  template:
    metadata:
      labels:
        app: broken-readiness-deployment
    spec:
      containers:
      - name: broken-readiness-deployment
        image: poznajkubernetes/pkad:blue
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: version
          value: v1
        readinessProbe:
          httpGet:
            path: /wrongurl
            port: 8080