apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-deployment
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recreate-deployment
  template:
    metadata:
      labels:
        app: recreate-deployment
    spec:
      containers:
      - name: recreate-deployment
        image: poznajkubernetes/pkad:blue
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: version
          value: v1
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080