apiVersion: v1
kind: Pod
metadata:
  name: additional-pod
  labels:
    app: replicaset-test
spec:
  containers:
  - name: additional-pod
    image: poznajkubernetes/helloapp:svc
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
