apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-probes
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: deployment-probes
  template:
    metadata:
      labels:
        app: deployment-probes
    spec:
      containers:
      - name: deployment-probes
        image: poznajkubernetes/helloapp:svc
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"