apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-multiple-labels
spec:
  replicas: 2
  selector:
    matchLabels:
      app: replicaset-multiple-labels
      env: production
  template:
    metadata:
      labels:
        app: replicaset-multiple-labels
    spec:
      containers:
      - name: replicaset-multiple-labels
        image: poznajkubernetes/helloapp:svc
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"