apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-additional-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: replicaset-test
  template:
    metadata:
      labels:
        app: replicaset-test
    spec:
      containers:
      - name: replicaset-additional-pod
        image: poznajkubernetes/helloapp:svc
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"